# plotly Data Viz ( Part-1)

In [19]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
%matplotlib inline

In [20]:
names= ['nimra','zubair','saliha']
heights=[5.2,5.7,5.2]

In [21]:

fig= px.line(x=names,y=heights,title= 'names and with person height')

fig.show()

In [22]:
fig= px.bar(x=names,y=heights,title= 'names and with person height')

fig.show()
# save the plot in png file 
fig.write_image('plotly_Bar.png')

C:\Users\Zubair Bajwa\AppData\Local\Temp\ipykernel_5044\3129633882.py:5: DeprecationWarning:


Support for Kaleido versions less than 1.0.0 is deprecated and will be removed after September 2025.
Please upgrade Kaleido to version 1.0.0 or greater (`pip install 'kaleido>=1.0.0'` or `pip install 'plotly[kaleido]'`).

In [23]:
df= sns.load_dataset('titanic')

In [24]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [26]:
df.dropna(inplace=True)
fig= px.scatter(df,x='age',y='fare',title='titanic dataset plot',color='sex',size='age')
fig.show()
fig.write_image('./outputs/02_plotly_Bar.png',scale=3)

C:\Users\Zubair Bajwa\AppData\Local\Temp\ipykernel_5044\3206073780.py:4: DeprecationWarning:


Support for Kaleido versions less than 1.0.0 is deprecated and will be removed after September 2025.
Please upgrade Kaleido to version 1.0.0 or greater (`pip install 'kaleido>=1.0.0'` or `pip install 'plotly[kaleido]'`).

In [30]:
# lets go with go objects
import plotly.graph_objects as go
# create simple plot 

fig = go.Figure(data=go.Scatter(x=[1,2,3,4],y=[10,10,20,30]))
fig.show()

In [33]:
# customize the upper plot
fig.update_layout(
    title= 'line plot of dummy dara',
    xaxis=dict(title='number'),
    yaxis= dict(title='values'),
    showlegend= True
)
fig.show()

In [35]:
# lets go with go objects
import plotly.graph_objects as go
# create simple plot 

fig = go.Figure(data=go.Scatter(x=df['age'],y=df['fare']))
fig.show()

In [37]:
# making heat map
data= np.random.rand(10,10)
heatmap= go.Heatmap(z=data)
fig= go.Figure(data=[heatmap])
fig.show()

In [39]:
df[['age','fare']].corr()

          age     fare
age   1.00000 -0.09073
fare -0.09073  1.00000

In [38]:
fig= px.imshow(df[['age','fare']].corr())
fig.show()

In [40]:
# iris
iris= sns.load_dataset('iris')
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [42]:
iris.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [45]:
fig= px.imshow(iris[[ 'sepal_length', 'sepal_width', 'petal_length', 'petal_width']].corr())
fig.show()